### ISSUE TITLE
Annotator Group Routing and landing page

### ISSUE THREAD

**Issue by BryonLewis** [umd-annotation/umd-annotation-tool#25]
Adding an annotator group and landing page for members of the group where they will be taken to a specific location where they will need direct URLs for their annotation system.

Add an exit button to the Annotation viewer which will take them back to their annotator group landing page.

**Comment by waxlamp** [comment]
We should think about this some more. The landing page is a good idea, but the exit button going back to the landing page may not make for a smooth workflow (they would need to go back to the spreadsheet, from where they would be opening a new window, and would need to close the old one anyway).

**Comment by BryonLewis** [comment]
Yeah, I think having the landing page should be used for annotators so that when they log in it doesn't take them to their home directory where they can mess around. 
I also agree the close or exit button should just close the tab for the annotator.
