### ISSUE TITLE
Watchtower Push Updates

### ISSUE THREAD

**Issue by BryonLewis** [umd-annotation/umd-annotation-tool#36]
Copying information from #35 about how to implement.

https://containrrr.dev/watchtower/lifecycle-hooks/
To do manual updates I think I would need to use watchtower lifecycle hooks which would run a script within the container and determine if the container should be updated. This would be a shell script which would check for the existence of a file on the OS or some flag that is set and return the proper exit code to enable the update. If the file/flag doesn't exist it returns an exit code of 75 to prevent updating.
This would require that we have the update frequency a bit higher like once every hour, but would require an admin action on the server to indicate that it should update.

**Comment by waxlamp** [comment]
Can we use this? https://containrrr.dev/watchtower/arguments/#run_once

**Comment by BryonLewis** [comment]
The run_once looks like you need access to the server, and is used for running a docker command.  I don't believe it is the type of argument you would put in a docker-compose file.

Thanks for that link.  Right below that is https://containrrr.dev/watchtower/arguments/#http_api_mode which allows you to specify a token and use an HTTP request with that token to force an update.
This still requires that you have a custom env file on the production server with the token and that we know about the token value and that we expose ports for access to that endpoint to trigger the updates.

The solution of adding it into DIVE admin doesn't require integration with Devops for server deployment or them having to do anything custom.

**Comment by BryonLewis** [comment]
As with most things not thinking about it for while made me come to the insanely simple solution.

You can use HTTP Mode and rolling updates at the same time using a specific environment variable: `- WATCHTOWER_HTTP_API_PERIODIC_POLLS=true`

The HTTP mode while it requires a token, that token can be public if we don't publish the ports to the container (8080 by default).  So that way the girder container can just call a post request to `http:watchtower:8080/v1/update` and it will cause it to pull the latest containers.
