### ISSUE TITLE
S3 Import Admin Panel

### ISSUE THREAD

**Issue by BryonLewis** [umd-annotation/umd-annotation-tool#72]
Provide a panel under the Admin settings to allow Importing/Updating S3 bucket imports.
The tool should contain a list of assetstores of the S3 type.
Each S3 asset store has an option for a destination folderId to import the S3 data to.
Once an asset store has been imported it saves the folderId to a backend setting.
On subsequent loads of this panel if the S3 has been imported to a specific folderId the folderId is prepopulated so it can prepopulate the destination folderId field.

**Comment by BryonLewis** [comment]
Closed with PR #70

**Comment by waxlamp** [comment]
I don't think this *specific* issue has been solved--we didn't add UI to execute the reimport, just the reimport process itself, right?
